In [1]:
import os
from PIL import Image
import time
import sys
import random

import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams['figure.figsize'] = [5, 5]
matplotlib.rcParams['figure.dpi'] = 200

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau

from data_helper import UnlabeledDataset, LabeledDataset
from helper import collate_fn, draw_box
from sklearn.metrics import confusion_matrix
from scipy.optimize import linear_sum_assignment

random.seed(0)
np.random.seed(0)
torch.manual_seed(0);

# All the images are saved in image_folder
# All the labels are saved in the annotation_csv file
image_folder = '../../DLSP20Dataset/data'
annotation_csv = '../../DLSP20Dataset/data/annotation.csv'


# All the images are saved in image_folder
# All the labels are saved in the annotation_csv file
#image_folder = '../../data'
#annotation_csv = '../../data/annotation.csv'

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

#device = 'cpu'

#device = "cpu"

torch.cuda.is_available()

# function to count number of parameters
def get_n_params(model):
    np=0
    for p in list(model.parameters()):
        np += p.nelement()
    return np

def order_points(pts):
    from scipy.spatial import distance as dist
    import numpy as np
    
    xSorted = pts[np.argsort(pts[:, 0]), :]

    leftMost = xSorted[:2, :]
    rightMost = xSorted[2:, :]

    leftMost = leftMost[np.argsort(leftMost[:, 1]), :]
    (tl, bl) = leftMost

    D = dist.cdist(tl[np.newaxis], rightMost, "euclidean")[0]
    (br, tr) = rightMost[np.argsort(D)[::-1], :]

    return np.array([tl, tr, br, bl]).astype(float)

def arrange_box(x1,y1):
    box=np.array(list(zip(x1,y1)))
    box=order_points(box)
    return box

def iou(box1, box2):
    from shapely.geometry import Polygon
    a = Polygon(torch.t(box1)).convex_hull
    b = Polygon(torch.t(box2)).convex_hull
    
    return a.intersection(b).area / a.union(b).area

#def iou(xy1,xy2):
#    
#    from shapely.geometry import Polygon
#    
#    boxA = Polygon(arrange_box(xy1[0],xy1[1])).buffer(1e-9)
#    boxB = Polygon(arrange_box(xy2[0],xy2[1])).buffer(1e-9)
#    
#    try:
#        return boxA.intersection(boxB).area / boxA.union(boxB).area
#    except:
#        print('Box 1:',xy1[0],xy1[1])
#        print('Box 2:',xy2[0],xy2[1])
#        sys.exit(1)

def map_to_ground_truth(overlaps, print_it=False):
    prior_overlap, prior_idx = overlaps.max(1)
    if print_it: print(prior_overlap)
#     pdb.set_trace()
    gt_overlap, gt_idx = overlaps.max(0)
    gt_overlap[prior_idx] = 1.99
    for i,o in enumerate(prior_idx): gt_idx[o] = i
    return gt_overlap,gt_idx

def calculate_overlap(target_bb, predicted_bb):
    overlaps = torch.zeros(target_bb.size(0),predicted_bb.size(0))

    for j in range(overlaps.shape[0]):
        for k in range(overlaps.shape[1]):
            overlaps[j][k] = iou(target_bb[j],predicted_bb[k])
            
    return overlaps

def one_hot_embedding(labels, num_classes):
    return torch.eye(num_classes)[labels.data.cpu()]

from skimage import draw
import numpy as np

def poly2mask(vertex_row_coords, vertex_col_coords, shape):
    fill_row_coords, fill_col_coords = draw.polygon(vertex_row_coords, vertex_col_coords, shape)
    mask = torch.zeros(shape, dtype=np.bool)
    mask[fill_row_coords, fill_col_coords] = True
    return mask

def convert_to_binary_mask(corners, shape=(800,800)):
    point_squence = torch.stack([corners[:, 0], corners[:, 1], corners[:, 3], corners[:, 2], corners[:, 0]])
    x,y = point_squence.T[0].detach() * 10 + 400, -point_squence.T[1].detach() * 10 + 400
    new_im = poly2mask(y, x, shape)
    return new_im

def create_conf_matrix(target, pred, debug=True):
    import sys
    
    target = target.reshape(-1)
    pred = pred.reshape(-1)
    
    if debug:
        print('Target values:', target.unique())
        print('Predicted values:', pred.unique())
        print('Target shape:', target.shape)
        print('Predicted shape:', pred.shape)
    
    nb_classes = max(target.unique())
    if len(pred.unique()) > (nb_classes+1) :
        print('More predicted classes than true classes')
        sys.exit(1)
        
    conf_matrix = torch.zeros(nb_classes+1, nb_classes+1)
    for t, p in zip(target, pred):
        conf_matrix[t, p] += 1
    
    return conf_matrix

def create_conf_matrix2(target, pred, debug=True):
    import sys
    
    target = target.reshape(-1).cpu().numpy()
    pred = pred.reshape(-1).cpu().numpy()
    
        
    conf_matrix = torch.from_numpy(confusion_matrix(target, pred)).to(device)
    
    return conf_matrix

def classScores(conf_matrix):
    print('Confusion matrix\n', conf_matrix)
    TP = conf_matrix.diag()
    TN = torch.zeros_like(TP)
    FP = torch.zeros_like(TP)
    FN = torch.zeros_like(TP)
    for c in range(conf_matrix.size(0)):
        idx = torch.ones(conf_matrix.size(0)).byte()
        idx[c] = 0
        # all non-class samples classified as non-class
        TN[c] = conf_matrix[idx.nonzero()[:, None], idx.nonzero()].sum() #conf_matrix[idx[:, None], idx].sum() - conf_matrix[idx, c].sum()
        # all non-class samples classified as class
        FP[c] = conf_matrix[idx, c].sum()
        # all class samples not classified as class
        FN[c] = conf_matrix[c, idx].sum()

        print('Class {}\nTP {}, TN {}, FP {}, FN {}'.format(
            c, TP[c], TN[c], FP[c], FN[c]))
        
    return TP, TN, FP, FN

def IOU(bbox1, bbox2):
    '''Calculate overlap between two bounding boxes [x, y, w, h] as the area of intersection over the area of unity'''
    x1, y1, w1, h1 = bbox1[0], bbox1[1], bbox1[2], bbox1[3]  # TODO: Check if its more performant if tensor elements are accessed directly below.
    x2, y2, w2, h2 = bbox2[0], bbox2[1], bbox2[2], bbox2[3]

    w_I = min(x1 + w1, x2 + w2) - max(x1, x2)
    h_I = min(y1 + h1, y2 + h2) - max(y1, y2)
    w_I = max(w_I, 0)  # set w_I and h_I zero if there is no intersection
    h_I = max(h_I, 0)
    I = w_I * h_I

    U = w1 * h1 + w2 * h2 - I

    return I / U

def dist(bbox1, bbox2):
    return torch.sqrt(torch.sum(torch.square(bbox1[:2] - bbox2[:2])))

# Dataset

# You shouldn't change the unlabeled_scene_index
# The first 106 scenes are unlabeled
unlabeled_scene_index = np.arange(106)
# The scenes from 106 - 133 are labeled
# You should devide the labeled_scene_index into two subsets (training and validation)
labeled_scene_index = np.arange(106, 134)

train_scene_index = np.random.choice(labeled_scene_index, int(np.ceil(0.1*len(labeled_scene_index))))

#test_scene_index = labeled_scene_index[np.isin(labeled_scene_index, train_scene_index,invert=True)]
test_scene_index = train_scene_index


transform=torchvision.transforms.Compose([torchvision.transforms.Resize((100,100)),
                                          torchvision.transforms.ToTensor(),
                              #torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                             ])


# Labeled dataset

batch_size = 1

NUM_SAMPLE_PER_SCENE = 126
NUM_IMAGE_PER_SAMPLE = 6
image_names = [
    'CAM_FRONT_LEFT.jpeg',
    'CAM_FRONT.jpeg',
    'CAM_FRONT_RIGHT.jpeg',
    'CAM_BACK_LEFT.jpeg',
    'CAM_BACK.jpeg',
    'CAM_BACK_RIGHT.jpeg',
    ]

def boxToHWC(boxes1):
    boxes1_max_x = boxes1[:, 0].max(dim=1)[0]
    boxes1_min_x = boxes1[:, 0].min(dim=1)[0]
    boxes1_max_y = boxes1[:, 1].max(dim=1)[0]
    boxes1_min_y = boxes1[:, 1].min(dim=1)[0]
    
    x = (boxes1_max_x + boxes1_min_x)/2
    y = (boxes1_max_y + boxes1_min_y)/2
    h = (boxes1_max_y - boxes1_min_y)
    w = (boxes1_max_x - boxes1_min_x)
    
    return torch.stack((x,y,h,w)).T


def imgToHWC(img):
    height, width = img.shape[:2]     
    x1 = int(row['XMin'] * width)     
    x2 = int(row['XMax'] * width)     
    y1 = int(row['YMin'] * height)     
    y2 = int(row['YMax'] * height)
    return (x1+x2)/2, (y1+y2)/2, height, width


def transformTargetstoHWC(targets):
    bounding_box = targets["bounding_box"]
    max, ind = torch.max(bounding_box, dim=3)
    min, ind = torch.min(bounding_box, dim=3)
    c = (400 + ((max + min)/2) * 10) / 1.92
    w = (max - min) * 10 / 1.92
    target = torch.cat((c, w), dim=2)
    category = targets["category"]
    targets = torch.cat((target, category.unsqueeze(2).double()), dim=2).float()
    target_lengths = torch.tensor(targets.numpy().shape[:2])
    return targets, target_lengths


# The dataset class for labeled data.
class LabeledSSDDataset(torch.utils.data.Dataset):    
    def __init__(self, image_folder, annotation_file, scene_index, transform, extra_info=True):
        """
        Args:
            image_folder (string): the location of the image folder
            annotation_file (string): the location of the annotations
            scene_index (list): a list of scene indices for the unlabeled data 
            transform (Transform): The function to process the image
            extra_info (Boolean): whether you want the extra information
        """
        
        self.image_folder = image_folder
        self.annotation_dataframe = pd.read_csv(annotation_file)
        self.scene_index = scene_index
        self.transform = transform
        self.extra_info = extra_info
    
    def __len__(self):
        return self.scene_index.size * NUM_SAMPLE_PER_SCENE

    def __getitem__(self, index):
        scene_id = self.scene_index[index // NUM_SAMPLE_PER_SCENE]
        sample_id = index % NUM_SAMPLE_PER_SCENE
        sample_path = os.path.join(self.image_folder, f'scene_{scene_id}', f'sample_{sample_id}') 

        images = []
        for image_name in image_names:
            image_path = os.path.join(sample_path, image_name)
            image = Image.open(image_path)
            images.append(self.transform(image))
        image_tensor = torch.stack(images)

        data_entries = self.annotation_dataframe[(self.annotation_dataframe['scene'] == scene_id) & (self.annotation_dataframe['sample'] == sample_id)]
        corners = data_entries[['fl_x', 'fr_x', 'bl_x', 'br_x', 'fl_y', 'fr_y','bl_y', 'br_y']].to_numpy()
        categories = data_entries.category_id.to_numpy()
        
        ego_path = os.path.join(sample_path, 'ego.png')
        ego_image = Image.open(ego_path)
        ego_image = torchvision.transforms.functional.to_tensor(ego_image)
        #road_image = convert_map_to_road_map(ego_image)
        
        target = {}
        target['bounding_box'] = torch.as_tensor(corners).view(-1, 2, 4)
        target['category'] = torch.as_tensor(categories).view(1,-1)
        
        target['chw'] = boxToHWC(target['bounding_box']).unsqueeze(0).double()


        return image_tensor, target['chw'], target['category']
        

# The labeled dataset can only be retrieved by sample.
# And all the returned data are tuple of tensors, since bounding boxes may have different size
# You can choose whether the loader returns the extra_info. It is optional. You don't have to use it.
labeled_trainset = LabeledSSDDataset(image_folder=image_folder,
                                  annotation_file=annotation_csv,
                                  scene_index=train_scene_index,
                                  transform=transform,
                                  extra_info=True
                                 )

trainloader = torch.utils.data.DataLoader(labeled_trainset, 
                                          batch_size=batch_size, 
                                          shuffle=True, 
                                          num_workers=0, 
                                          collate_fn=collate_fn)

labeled_testset = LabeledSSDDataset(image_folder=image_folder,
                                  annotation_file=annotation_csv,
                                  scene_index=test_scene_index,
                                  transform=transform,
                                  extra_info=True
                                 )

testloader = torch.utils.data.DataLoader(labeled_testset, 
                                          batch_size=batch_size, 
                                          shuffle=True, 
                                          num_workers=0, 
                                          collate_fn=collate_fn)

def double_conv(in_channels, out_channels):
    return nn.Sequential(
        nn.Conv2d(in_channels, out_channels, 3, padding=1),
        nn.LeakyReLU(negative_slope=0.1),
        nn.BatchNorm2d(out_channels),
        #nn.Dropout(0.5),
        nn.Conv2d(out_channels, out_channels, 3, padding=1),
        nn.LeakyReLU(negative_slope=0.1),
        nn.BatchNorm2d(out_channels),
        #nn.Dropout(0.5)
    ) 


class CNN(nn.Module):
    def __init__(self, d=650, output_size=4):
        super().__init__()
        self.dconv_down1 = double_conv(3, 16)
        self.dconv_down2 = double_conv(16, 32)
        self.dconv_down3 = double_conv(32, 48)
        self.dconv_down4 = double_conv(48, 64)        
        self.maxpool = nn.MaxPool2d(2)
        self.linear1 = nn.Linear(6*64*12*12,4*88) ## 88 boxes
        self.linear2 = nn.Linear(6*64*12*12,88) ## 88 boxes
        
    def forward_once(self, x):
        conv1 = self.dconv_down1(x)
        x = self.maxpool(conv1)


        conv2 = self.dconv_down2(x)
        x = self.maxpool(conv2)

        
        conv3 = self.dconv_down3(x)
        x = self.maxpool(conv3)  

        
        x = self.dconv_down4(x)
        return x
    
    def forward(self,x):
        x = [self.forward_once(y) for y in x]
        x = torch.cat(x,axis=1)
        x1 = self.linear1(x.reshape(-1,6*64*12*12))
        x2 = self.linear2(x.reshape(-1,6*64*12*12))
        return (x1,F.sigmoid(x2))

In [2]:
model = CNN()

mse = nn.MSELoss()

learning_rate = 3e-4

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

best_loss = 1000000000000000
num_epochs = 10
threshold = 0.5

In [ ]:
num_objects = 88

for epoch in range(0, num_epochs):
    model.train()
    train_loss = {}
    train_loss['boxes'] = 0
    train_loss['probs'] = 0
    train_loss['total'] = 0
    for (x, bb_true, class_true) in trainloader:
        exp = torch.stack(bb_true)
        pred, probs = model(torch.stack(x).reshape(6,-1,3,100,100))
        pred = pred.reshape(1,-1,4)
        probs = probs.reshape(1,-1,88)
        
        num_true = exp.size(2)
        pred = pred.reshape(num_objects, -1)
        exp = exp.reshape(num_true, -1)
        pred_bboxes = pred[:, :4]
        exp_bboxes = exp[:, :4]
        # TODO: Try flipping array and see if results differ.
        ious = np.zeros((num_true, num_objects))
        for i, exp_bbox in enumerate(exp_bboxes):
            for j, pred_bbox in enumerate(pred_bboxes):
                ious[i, j] = IOU(exp_bbox, pred_bbox)

        exp_idx, pred_idx = linear_sum_assignment(-ious)

        loss1 = mse(exp[exp_idx],pred[pred_idx])
        train_loss['boxes'] += loss1.item()
            
        label = torch.zeros(88)
        label[pred_idx] = 1
        loss2 = mse(probs.reshape(-1), label.reshape(-1))
        train_loss['probs'] = loss2.item()
        
        loss = loss1 + loss2
        
        train_loss['total'] = loss.item()
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    print('====> Epoch: {} Average loss (boxes): {} / {}'.format(
    epoch,train_loss['boxes'],len(trainloader.dataset)))
    print('====> Epoch: {} Average loss (probs): {} / {}'.format(
    epoch,train_loss['probs'],len(trainloader.dataset)))
    print('====> Epoch: {} Average loss (total): {} / {}'.format(
    epoch,train_loss['total'],len(trainloader.dataset)))
    
    with torch.no_grad():
        model.eval()
        test_loss = {}
        test_loss['boxes'] = 0
        test_loss['probs'] = 0
        test_loss['total'] = 0
        for (x, bb_true, class_true) in testloader:
            exp = torch.stack(bb_true)
            pred, probs = model(torch.stack(x).reshape(6,-1,3,100,100))
            pred = pred.reshape(1,-1,4)
            probs = probs.reshape(1,-1,88)
            num_preds = exp.size(2)
            pred = pred.reshape(num_objects, -1)
            exp = exp.reshape(num_preds, -1)
            pred_bboxes = pred[:, :4]
            exp_bboxes = exp[:, :4]

            pred_idx = (probs>threshold).squeeze()
            print(pred_idx)
            predicted_boxes = pred[pred_idx]
            print(predicted_boxes)
            predicted_num_objects = torch.sum(probs>threshold)
            ious = np.zeros((num_preds, predicted_num_objects))
            for i, exp_bbox in enumerate(exp_bboxes):
                for j, pred_bbox in enumerate(predicted_boxes):
                    ious[i, j] = IOU(exp_bbox, pred_bbox)
                    
            print(np.mean(ious))

            

====> Epoch: 0 Average loss (boxes): 70111.21628114417 / 378
====> Epoch: 0 Average loss (probs): 0.206088587641716 / 378
====> Epoch: 0 Average loss (total): 162.36143132149786 / 378
tensor([False,  True,  True, False, False,  True, False, False, False, False,
         True, False, False,  True, False,  True, False,  True, False, False,
        False, False,  True, False,  True,  True,  True, False, False, False,
        False, False, False,  True,  True, False, False,  True, False, False,
        False, False, False, False, False, False, False,  True,  True, False,
         True, False,  True, False,  True, False, False,  True, False, False,
        False, False,  True, False, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True])
tensor([[ -5.5389,  11.0793,   6.3388,   3.1887],
        [ -9.5666,  -9.6823,   7.9729,  10.0772],
        [-11.1722,   6.7030

0.00026484904944194376
tensor([False,  True, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False,  True, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True, False,
        False, False, False,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[-3.7052e+00,  5.1343e+00,  1.3586e+00,  2.3443e+00],
        [-1.0422e+01,  3.4988e+00,  1.2493e+00, -5.4256e+00],
        [ 2.4630e+01,  2.6124e+01, -2.1825e+01,  8.6610e-01],
        [-2.1264e+01,  1.7464e+01,  1.3428e+01, -3.8163e+00],
        [ 4.8040e+00,  7.9741e+00,  1.49

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 24.5794,  27.4500, -24.5926,   2.3097],
        [  0.3178,   0.3797,   0.9333,  -0.6759],
        [  4.1707,  -1.6997,  -9.4266,   3.2188],
        [  1.5929,   1.2718,  -1.9473,  10.9097],
        [ 13.8282,   9.5813,  -5.3428,   6.7422],
        [  3.1898,  21.7509,   2.7260,   9.0847],
        [ 1

0.00010210090587959851
tensor([False,  True, False, False, False, False, False, False, False, False,
        False, False,  True, False, False,  True, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False, False, False,  True,  True,
        False, False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True, False,
         True, False,  True,  True,  True,  True,  True,  True])
tensor([[-7.4742e+00, -1.1354e+00,  6.9547e+00,  4.0055e+00],
        [-2.0230e-01,  5.5196e-01,  9.2244e-02, -4.0826e-01],
        [-4.6432e+00,  1.7075e-01, -2.1027e+00, -3.7376e+00],
        [ 1.0195e+01,  4.4591e+00, -1.6433e+00, -1.9489e-01],
        [ 9.4726e-03, -2.4440e-01,  3.60

0.0016341423186402493
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  1.3666,   2.0069,   4.1458,  -0.6017],
        [-25.4510,  32.0224,   4.8488,   2.1845],
        [ 12.1799,  15.5598,   9.5758,   3.1747],
        [ -6.0057,  12.3430,  12.9364,  10.0891],
        [ -9.5853,   6.0465,  -1.9889,   4.4008],
        [ 17.6302,  20.1771,  -2.2055, 

0.0012615630424777848
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ -3.0289,  10.9056,  -5.3762,  -6.8126],
        [ 17.2495,   0.4756,  -3.8221,   6.3438],
        [ -2.9061,   4.3021,   9.7290,   3.1918],
        [ -3.7105,  11.3344, -10.1179,   8.0560],
        [ -3.4527,   1.2716,   3.6565,   4.7956],
        [ -0.7846,  13.7716,   9.3425, 

0.0003176728925852137
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  1.0687,   0.4093,   3.7409,   5.4427],
        [ -4.1866,  -2.7969,   1.9583,   4.1969],
        [  3.3634,   3.8915,  -1.9473,   5.3709],
        [  0.7566,   2.5799,   3.1020,   5.5823],
        [ -4.1815,  16.3588,  -1.2943,   7.4031],
        [ 11.6590,   0.6596,   1.4622, 

0.0005851973558375307
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True, False,  True,  True,  True,  True, False,
        False,  True, False, False,  True,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True])
tensor([[ 10.2968,   5.6526,   4.9495,   4.3125],
        [ 13.7088,  -1.5228,   0.6911,  -0.1124],
        [ -6.5736,   0.4656,  -3.9708,  11.4791],
        [  3.5267,  -3.9588,   1.7985,   2.7542],
        [  5.2269,  -4.0926,  -4.0772,  -1.1345],
        [ -4.9795,  -5.2866,  -6.3553, 

0.0013204255983263393
tensor([ True,  True, False, False, False, False, False, False, False, False,
         True, False, False, False, False,  True, False, False, False, False,
        False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False, False, False, False, False,
        False, False, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 1.4156e+01, -3.5333e+00, -1.1622e+01,  3.4913e+00],
        [-1.9656e+00,  6.2041e+00,  2.8899e-01,  4.0564e+00],
        [-1.7333e-01, -1.0343e+01,  9.1427e-01,  1.0786e+01],
        [-9.1876e+00,  7.1517e-01,  2.8863e+00, -3.1394e+00],
        [ 3.2604e+01,  3.5321e+01, -3.163

tensor([ True,  True,  True,  True, False, False, False, False, False, False,
         True, False,  True,  True, False,  True, False, False,  True, False,
        False,  True,  True,  True, False,  True,  True, False, False, False,
        False,  True, False, False,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
         True,  True, False, False,  True,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True])
tensor([[ 5.6316e+00, -9.1386e+00, -3.1467e+00,  4.2509e+00],
        [-2.7765e+00,  1.2403e+01,  1.0325e+00,  6.7266e+00],
        [ 9.2328e+00,  8.2891e+00, -1.0324e+01, -1.0144e+01],
        [-5.8089e-01,  3.5689e-01, -1.7089e+00,  9.5792e-01],
        [-7.1067e+00, -1.2726e+01,  2.8804e+00,  1.2599e+01],
 

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  0.3863,   3.8526,   0.2508,   4.0358],
        [ 10.4788,  -3.5318,   2.9211,   0.0664],
        [  8.6776,   2.9407,  -0.3566,   0.6224],
        [  3.5328, -11.6370,   6.2491,   2.4462],
        [ -8.8676, -11.0482,   4.2156,   2.1384],
        [ -2.4988,  11.6456,   1.2814,  11.0413],
        [  

0.0006107628144793309
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False, False,
         True, False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  4.2145,  -7.8162,   3.6441,   3.6486],
        [ 13.4284,  18.5405,  -2.7064,  -3.5539],
        [ -0.6201,   2.0690,  11.0268,   3.3148],
        [  8.7388,   1.0657,   7.0501,   4.6316],
        [ -1.2830, -15.0842,   1.3197,  10.9022],
        [ -6.6889,   7.2592,  14.3217, 

0.0009511120032318232
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 5.1189, -1.7012, -0.6040,  4.4296],
        [ 1.5567,  1.0378, -0.6695,  4.4865],
        [ 9.9664, -5.4932,  3.9228,  6.5826],
        [-8.4418, -7.2577,  1.9876,  7.8841],
        [-2.4575,  6.9679, -1.5844,  9.8137],
        [ 4.9752,  2.1396,  4.4284,  8.3961],
        [12.0

0.000757952816864439
tensor([False, False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False,  True,  True,  True,  True,  True,
        False,  True, False, False,  True,  True, False, False, False, False,
        False, False,  True,  True,  True,  True,  True,  True])
tensor([[  7.7077,  -5.7438,  -4.0526,   6.6979],
        [  0.8654,   0.5534,  -0.2151,  -0.1779],
        [ 10.1778,   4.1438,   2.7590,   2.7810],
        [ -0.2452,   4.3913,   2.2163,   3.7916],
        [ -4.6322,  -6.9192,  -0.4300,   1.6762],
        [  5.4010, -12.0070,   4.6963,  

0.0008568426834713302
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False,  True, False,  True,  True,  True,  True,  True,
         True,  True, False, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 19.4955,  11.0043,  -6.7810,  -6.1740],
        [  9.5458,   6.1357,  -5.9893,   2.3835],
        [ 12.0969,  -6.5779,  -0.5820,   2.3741],
        [  5.7480,  -9.4968,   1.1906,  -2.7514],
        [-14.8200,  -8.6354,   0.2592,   9.9872],
        [ -0.2337,  10.0931,   0.4048, 

0.000856936020836466
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 8.0369e+00,  3.6380e+00,  8.2409e+00,  5.7294e+00],
        [-7.1654e+00, -9.8360e+00,  7.2009e+00, -1.4977e+00],
        [ 5.0139e+00,  1.1524e+00, -2.3192e+00,  3.8150e+00],
        [ 2.9052e+00, -3.9456e+00,  2.1414e+00,  3.1979e+00],
        [ 6.6083e+00, -1.5336e+00,  2.3505

0.0008131315840667256
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ -0.5040,   0.0363,  -2.6876,  -2.4507],
        [ -4.9092,   3.1680,   0.4665,   4.5190],
        [  6.4016, -11.2754,  -1.2208,   4.0644],
        [-11.2006,  21.8235,  -0.6927,   4.6495],
        [ 21.2740,  -0.9631,   4.7749,   0.9008],
        [  4.3158,   0.9605,   9.3992, 

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[  5.2677,   2.0587,   2.8108,   1.9284],
        [ 18.7304,  -5.2615,   1.5580,  -0.6420],
        [ 13.9954,   0.6972,  -1.0891,  -2.6472],
        [ -6.4183,   5.2541,  -0.4677,  -1.0895],
        [ -0.9489,  -8.3405,  -0.1924,   0.7932],
        [ -5.4848,  -8.1745,  -1.2480,   5.3032],
        [ -

0.0003119154596729506
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False,  True, False, False, False,
         True, False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  7.4916,  -5.6405,   4.2824,   2.5213],
        [ -1.2700,  -6.9786,   6.2241,   4.2576],
        [ 16.0198,   2.6900,   2.7814,   0.6642],
        [  0.8023,  -5.2005,  -2.1298,   9.1949],
        [ -1.0875,   4.1133,  12.5811,   7.0542],
        [  6.1835,   1.2740,   9.1779, 

0.0007720171289534017
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  5.9280,  -4.2391,  -1.4188,   3.7108],
        [ 17.0996,  10.7947,   8.5513,   3.0222],
        [ -8.8094,   3.6974,  12.4142,   4.3246],
        [ -0.7719,   7.4497,  -0.5943,   9.8520],
        [ -0.5298,   5.9799,  -1.2856,   5.9776],
        [  0.4583,   6.9115,   3.3882, 

0.00043432130706831434
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False,  True, False,  True, False,  True, False,  True,  True, False,
        False,  True, False, False,  True,  True,  True,  True, False,  True,
        False, False, False,  True,  True,  True,  True,  True])
tensor([[ 1.7337e+01, -7.5170e+00,  1.0620e+00,  9.7367e-01],
        [ 1.2882e+00, -2.8526e+00, -8.7076e-01,  3.9476e+00],
        [ 1.0276e+00, -8.1768e+00, -2.6961e+00, -2.8179e+00],
        [ 6.3590e+00, -2.8584e+00, -5.7354e+00,  3.6043e+00],
        [-4.1399e-01,  7.1571e+00, -7.41

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True,  True,  True])
tensor([[ 12.1575,  -6.4337,   6.6402,  -1.1191],
        [ -6.6505,  -5.4405,  -4.3900,   3.5498],
        [  2.9044,   1.2083,  -0.2581,   4.3823],
        [  7.5194,   5.6472,   4.3510,  11.9930],
        [ -6.0607,  17.0405,   2.0304,   1.0858],
        [ 17.9400,   1.6097,   1.3313,   1.4779],
        [-1

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True, False,
         True, False, False,  True, False, False, False, False, False, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 2.1319e+01,  1.1616e+01, -8.4425e+00, -2.5978e+00],
        [ 3.3885e+00,  1.0735e+01, -3.1518e+00, -1.0784e+00],
        [ 2.0585e+00,  5.7087e+00,  2.1765e+00,  5.2182e+00],
        [ 1.4946e+00, -9.4593e+00,  1.7079e+00, -5.1592e+00],
        [-3.5676e+00,  2.0166e+00, -2.4162e+00, -5.9511e+00],
 

0.002524874213374322
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  2.7356,   4.5856,   3.0191,   9.1479],
        [  1.6785,   2.5081,  -6.9134,  -1.6550],
        [ -0.5376,  -1.5944,  -8.5612,   9.2245],
        [  3.2029,   1.9202,  -1.0460,   5.2543],
        [  1.7063,  15.2249,   6.2435,   8.0560],
        [ 17.7178,   2.0314,  -0.2678,  

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 11.4819,  13.0816,  -1.6295,   6.6062],
        [ -5.6632,  17.0789,   0.2763,   3.8396],
        [ 19.0822,   3.9814,  -3.6221,  10.5756],
        [ -9.6344,   8.4662,   9.0530,   2.7295],
        [ -7.2392,  11.6713,   5.4678,   7.2416],
        [  3.5496,  12.6921,   3.3798,  14.3262],
        [-1

tensor([False, False, False, False, False, False, False, False, False, False,
         True, False, False, False, False,  True, False, False, False, False,
        False, False,  True, False, False,  True,  True, False,  True, False,
        False,  True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
         True, False, False, False, False, False, False, False,  True, False,
        False,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[ -4.0734,  -2.9760,  -3.2758,   3.1548],
        [  1.4993,  -1.6301,  -0.8266,  -0.5337],
        [ 20.8568,  18.8485, -18.7674,  -3.2803],
        [-18.3172,   2.2672,  11.7506,  10.1613],
        [  0.1247,   0.8257,  -0.1353,  -0.7306],
        [ -1.1015,   7.8079,   8.2879,  -7.8410],
        [ -

tensor([False, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False,  True, False, False,
        False, False, False, False, False, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[-5.8763e+00,  3.9967e+00,  3.5519e-01,  1.3608e+00],
        [ 2.9897e+00,  2.6571e+00, -1.0033e+01,  2.9414e+00],
        [ 1.5616e-01,  3.7788e+00,  8.1600e+00, -9.1205e+00],
        [-3.8312e+00, -4.1408e+00,  3.7682e+00,  3.3641e+00],
        [ 6.8261e+00,  7.0538e+00,  5.0580e+00,  7.5746e+00],
 

0.0004941991538517447
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[ -6.2375,   2.6072,  -0.5213,  -6.8406],
        [  9.7718,  12.7372,  -0.1140,   4.1467],
        [ 17.6095,  -1.8103,  -2.1393,   5.5691],
        [-22.1635,  -0.6335,  -1.8232,   1.3004],
        [  0.4160,  -8.3584, -14.3191,   0.3715],
        [  0.8276,  18.9393,  10.7594, 

0.0014406073388330439
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True, False, False,  True, False,
        False, False,  True,  True,  True, False, False, False, False, False,
        False, False,  True,  True, False, False,  True,  True, False, False,
        False, False, False, False,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True])
tensor([[-4.1017e-01,  4.2474e-01,  5.0261e-01, -3.9130e-01],
        [-1.3643e+01, -9.5963e+00,  5.9429e+00, -2.6068e-03],
        [ 4.6889e+00, -3.5358e-01, -6.7230e+00, -5.8385e+00],
        [ 7.6944e-01,  8.2850e+00, -4.2531e-01,  3.7623e+00],
        [-1.3446e+01, -1.3538e+01,  4.643

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False, False, False,  True, False,
        False,  True, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  3.8097,   7.0791,   1.8562,   8.1402],
        [  4.7130,   3.2835,  -9.5096,  -1.9168],
        [ -3.6220,   1.8899,   3.3275,   3.1216],
        [  9.3577,  -3.6612,  -4.4658,  -3.8160],
        [ -5.0318,  -3.4493,  -7.2114,  10.3999],
        [  1.6551,  -2.5069,  -1.6885,   0.5268],
        [  

tensor([[ -4.4553, -12.5513,  -0.1508,  -0.6090],
        [  6.7489,   4.9824,   0.8351,   0.5704],
        [  0.4703,   3.1661,  -3.8611,   3.0363],
        [-17.7223,   2.2359,  -8.0950,  12.4130],
        [ 13.3489,  -7.6276,   4.6607,  10.2768],
        [-28.5892,  15.2803,  10.4996,  -7.0992],
        [ 17.6470,   7.1829,   9.9917,  12.1561],
        [  4.9775,  -3.4563,   3.5855,  18.0602],
        [ 15.1122, -13.0448,   0.3656,  10.7501],
        [-15.9365,  -0.0721,   2.8166,   2.2373],
        [  1.6770, -10.0766,  -1.5893,   3.0247],
        [ -9.7730,  -9.6784,   2.3068,   6.5850],
        [ -7.6851, -10.8322,   2.0410,   2.9866],
        [ -2.0477,   0.7646,  -5.1646,   4.2685],
        [  2.1550,  -1.0427,   6.0958,   7.2680],
        [  8.8197,  -5.1016,   0.6571,   8.4306],
        [  0.4615,   2.1873,   6.0271,   0.5082],
        [ -3.2816,  -2.5370,  -4.4916,   6.2852],
        [ -0.2167,   5.4666,   6.8411,   5.2898],
        [ 10.7552,   9.5039,   8.0157,  -0.4742],


0.001036567104461931
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 8.0971e+00,  9.2039e-01, -8.4366e+00,  1.8773e+00],
        [-2.4532e+00,  1.3165e+01,  3.6340e+00,  9.3438e+00],
        [ 3.0964e+01,  2.6413e+00,  9.7693e+00,  5.6145e+00],
        [ 4.9713e+00,  1.1523e+01, -6.8751e+00,  6.4136e+00],
        [-5.0179e+00,  1.2010e+01,  4.7062

0.0011583646040169908
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False, False,
         True, False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 5.1864e+00, -6.8388e+00, -1.8836e+00,  3.5720e+00],
        [ 1.3186e+01,  2.9878e+00, -1.6663e-01,  1.8204e+00],
        [ 5.5527e-01,  1.2718e+01,  5.6651e+00,  8.1184e+00],
        [ 6.7243e+00,  4.4848e-01,  5.9858e-01,  9.7982e+00],
        [-1.8286e+00,  1.6757e+00,  1.205

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False,  True, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False,  True,  True,  True,
         True,  True, False, False,  True,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True])
tensor([[ -8.7261,   1.5339,  -0.7166,  -5.6102],
        [ 18.4786,  24.5932, -18.8383,  -0.4385],
        [  0.4998,   0.9682,   0.5611,  -0.2658],
        [  0.2352,   8.1152,  -1.4225,   7.9879],
        [ -1.5869,  -5.5436,   1.9987,  -1.9811],
        [  2.7112,   4.1109,  -6.5786,   2.3244],
        [  

0.0021442267742617527
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
         True, False,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[ 14.2502,   0.8910,  -5.8397,  -5.7389],
        [ 10.9419,  -0.5223,  -7.2174,  -0.3357],
        [-24.7572,  52.1152, -35.9550,  33.4967],
        [ -0.6239,  26.6357,  -0.1573,  27.1392],
        [  4.0771,  -3.5351,  16.5857,  12.2844],
        [  5.0922,  -6.1216,  -7.9263, 

0.0006765978181570696
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  9.9683,  -5.5992,  -1.8017,   5.6236],
        [ -5.0755,  31.4389,   1.6594,  22.0503],
        [ 21.8430,   2.6636,   0.9525,   3.5125],
        [ -8.3877,   7.7595,  16.3587,   2.4231],
        [ -6.1297,   6.1632,  -3.2616,   3.7218],
        [ -1.1145,  15.0988,  -1.5380, 

0.0010042104261706309
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  6.3558,  -8.8456,   3.9501,   3.7906],
        [  1.0504,  -2.9251,  -0.8461,   5.5743],
        [-16.9550,  18.4358,   1.4717,   3.8995],
        [ 15.6811,  10.8286,  -8.2377,   8.6586],
        [ -4.7766,   6.1057,   7.9177,   4.1571],
        [ -4.2583,   6.1952,  -5.0336, 

0.0015814380781223503
tensor([False,  True, False, False, False, False, False, False, False, False,
         True, False,  True, False, False,  True, False, False, False, False,
        False, False,  True, False, False, False,  True, False,  True, False,
        False,  True, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True, False,
         True,  True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True])
tensor([[ -7.6017,  11.8183,   9.5444,  10.3724],
        [ -5.4582, -11.8982,  -3.2838,   9.6624],
        [ -0.1494,  -0.3137,   0.6310,  -0.1163],
        [ -5.2877,  -1.2737,   0.7873,  -1.9969],
        [ 30.3677,  36.4751, -19.9192,  12.7546],
        [ -0.7110,   0.2014,  -0.5082, 

0.001620386758287772
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False, False,
         True,  True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  5.9286,  -5.0145,   0.9565,   2.0764],
        [ 17.8319,  10.4078,   1.1437,   8.1121],
        [-11.5729,   3.5437,   7.2121,   3.8288],
        [  1.1666,   2.3194,  -0.8764,   6.0627],
        [  0.3444,  -7.4812,   1.9534,   5.0339],
        [  0.9988,  -6.1179,  12.2800,  

0.0005555567554307694
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True])
tensor([[  7.9616,  -0.6211, -10.5354,   2.1866],
        [ 26.7168,   5.4373,   6.2671,   8.6813],
        [ -4.1386,  12.2372,   6.1000,   0.5815],
        [ 12.7400,  16.3182,  -6.1244,   7.3427],
        [ -6.9010,  21.7176,   3.4802,  14.7980],
        [ -3.3477,   5.7192,  -0.2641, 

In [ ]:
pred_bboxes

In [ ]:
exp