In [1]:
import os
import time
import sys
import random
import psutil

import json
import copy
import numpy as np
import pandas as pd
from collections import Counter

from skimage.measure import label
from scipy.ndimage.morphology import distance_transform_edt

import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams['figure.figsize'] = [5, 5]
matplotlib.rcParams['figure.dpi'] = 200

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torch.optim as optim
from torch.nn import init
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.autograd import Variable
from collections import OrderedDict
from sklearn.metrics import confusion_matrix

from utils import create_conf_matrix2, split_list, convert_to_binary_mask, classScores
#if there is a utils folder change name above
from models import UNet2
from data_helper import UnlabeledDataset, LabeledDataset
from helper import collate_fn, draw_box
from loss_functions import loss_function_iou

random.seed(0)
np.random.seed(0)
torch.manual_seed(0);

# All the images are saved in image_folder
# All the labels are saved in the annotation_csv file
#image_folder = '../../DLSP20Dataset/data'
#annotation_csv = '../../DLSP20Dataset/data/annotation.csv'

#azure
image_folder = '../../data'
annotation_csv = '../../data/annotation.csv'


#device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device = 'cpu'

torch.cuda.is_available()

True

In [2]:
# You shouldn't change the unlabeled_scene_index
# The first 106 scenes are unlabeled
unlabeled_scene_index = np.arange(106)
# The scenes from 106 - 133 are labeled
# You should devide the labeled_scene_index into two subsets (training and validation)
labeled_scene_index = np.arange(106, 134)

train_scene_index = np.random.choice(labeled_scene_index, int(np.ceil(0.9*len(labeled_scene_index))))

test_scene_index = labeled_scene_index[np.isin(labeled_scene_index, train_scene_index, invert=True)]

val_scene_index, test_scene_index = split_list(test_scene_index)


transform=torchvision.transforms.Compose([torchvision.transforms.Resize((100,100)),
                                          torchvision.transforms.ToTensor(),
                              #torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                             ])

batch_size = 1

labeled_valset = LabeledDataset(image_folder=image_folder,
                                  annotation_file=annotation_csv,
                                  scene_index=val_scene_index,
                                  transform=transform,
                                  extra_info=True
                                 )

valloader = torch.utils.data.DataLoader(labeled_valset, 
                                          batch_size=batch_size, 
                                          shuffle=True, 
                                          num_workers=0, 
                                          collate_fn=collate_fn)

labeled_testset = LabeledDataset(image_folder=image_folder,
                                  annotation_file=annotation_csv,
                                  scene_index=test_scene_index,
                                  transform=transform,
                                  extra_info=True
                                 )

testloader = torch.utils.data.DataLoader(labeled_testset, 
                                          batch_size=batch_size, 
                                          shuffle=True, 
                                          num_workers=0, 
                                          collate_fn=collate_fn)

In [3]:
def validate_model_BB(model, num_points, loss_function, device=None, img_w=100, img_h=100):
    threshold_values = np.linspace(0.01,0.99,num_points)
    correct = [0]*num_points
    total = [0]*num_points
    accuracy_list = [None]*num_points
    threat_score_list = [None]*num_points
    conf_matrices = [torch.zeros(2,2).to(device),torch.zeros(2,2).to(device)]*num_points
    max_threat_score = 0
    opt_threshold = 0.5
    for k,threshold in enumerate(threshold_values):  
        with torch.no_grad():
            model.eval()
            test_loss = 0
            for batch_idx, data in enumerate(valloader):
                sample, target, road_image, extra = data
                batch_size = len(road_image)
                x = torch.zeros((batch_size,1,800,800))
                #x[:,0,:,:] = 1.0*torch.stack(road_image).reshape(-1, 800, 800)
                x[:,0,:,:] = torch.zeros((batch_size,800,800))
                for i in range(batch_size):
                    for cat, bb in zip(target[i]['category'], target[i]['bounding_box']):
                        x[i,0,:,:] = 1.0*convert_to_binary_mask(bb)
                x = x.to(device) 
                y = torch.stack(sample).reshape(6,-1,3,img_w,img_h).to(device)

                # ===================forward=====================
                x_hat = model(y)
                test_loss += loss_function(x_hat, x).item()
                # =====================log=======================

                i = 0
                correct[k] += (x_hat[:,i,:,:]>threshold).eq(
                    (x[:,i,:,:]==1).data.view_as((
                        x_hat[:,i,:,:]>threshold))).cpu().sum().item()
                total[k] += x[:,i,:,:].nelement()

                conf_matrices[k] += create_conf_matrix2(1*(x[:,i,:,:]==1), 1*(x_hat[:,i,:,:]>threshold), device=device)
                #print('='*100)


        accuracy_list[k] = 100. * correct[k] / total[k]
        TP, TN, FP, FN = classScores(conf_matrices[k])
        threat_score_list[k] = TP[1]*1.0/(TP[1]+FP[1]+FN[1])
        if threat_score_list[k] > max_threat_score:
            print('Updating threat score from {} to {}'.format(threat_score_list[k],max_threat_score))
            max_threat_score = threat_score_list[k]
            opt_threshold = threshold

        print("""\nValidation set: 
        Average loss: {:.9f}, 
        Accuracy BB: {}/{} ({:.9f}%) ,
        BB: 
        TP {} 
        TN {}
        FP {}
        FN {}
        Threat Score {}""".format(
            test_loss, 
            correct[k], total[k], accuracy_list[k],
             TP[1], TN[1], FP[1], FN[1], threat_score_list[k]))

        # ===================log========================
        test_loss /= len(testloader.dataset)
        print(f'====> Validation set loss: {test_loss:.9f}')
    return opt_threshold, max_threat_score

In [7]:
def validate_model_Road(model, num_points, loss_function, device=None, img_w=100, img_h=100, low=0.01, high=0.99):
    threshold_values = np.linspace(low,high,num_points)
    correct = [0]*num_points
    total = [0]*num_points
    accuracy_list = [None]*num_points
    threat_score_list = [None]*num_points
    conf_matrices = [torch.zeros(2,2).to(device),torch.zeros(2,2).to(device)]*num_points
    max_threat_score = 0
    opt_threshold = 0.5
    for k,threshold in enumerate(threshold_values):  
        with torch.no_grad():
            model.eval()
            test_loss = 0
            for batch_idx, data in enumerate(valloader):
                sample, target, road_image, extra = data
                batch_size = len(road_image)
                x = torch.zeros((batch_size,1,800,800))
                x[:,0,:,:] = 1.0*torch.stack(road_image).reshape(-1, 800, 800)
                #x[:,0,:,:] = torch.zeros((batch_size,800,800))
                #for i in range(batch_size):
                #    for cat, bb in zip(target[i]['category'], target[i]['bounding_box']):
                #        x[i,0,:,:] = 1.0*convert_to_binary_mask(bb)
                x = x.to(device) 
                y = torch.stack(sample).reshape(6,-1,3,img_w,img_h).to(device)

                # ===================forward=====================
                x_hat = model(y)
                test_loss += loss_function(x_hat, x, device=device).item()
                # =====================log=======================

                i = 0
                correct[k] += (x_hat[:,i,:,:]>threshold).eq(
                    (x[:,i,:,:]==1).data.view_as((
                        x_hat[:,i,:,:]>threshold))).cpu().sum().item()
                total[k] += x[:,i,:,:].nelement()

                conf_matrices[k] += create_conf_matrix2(1*(x[:,i,:,:]==1), 1*(x_hat[:,i,:,:]>threshold), device=device)
                #print('='*100)


        accuracy_list[k] = 100. * correct[k] / total[k]
        TP, TN, FP, FN = classScores(conf_matrices[k])
        threat_score_list[k] = TP[1]*1.0/(TP[1]+FP[1]+FN[1])
        if threat_score_list[k] > max_threat_score:
            print('Updating threat score from {} to {}'.format(threat_score_list[k],max_threat_score))
            max_threat_score = threat_score_list[k]
            opt_threshold = threshold

        print("""\nValidation set: 
        Average loss: {:.9f}, 
        Accuracy BB: {}/{} ({:.9f}%) ,
        BB: 
        TP {} 
        TN {}
        FP {}
        FN {}
        Threat Score {}""".format(
            test_loss, 
            correct[k], total[k], accuracy_list[k],
             TP[1], TN[1], FP[1], FN[1], threat_score_list[k]))

        # ===================log========================
        test_loss /= len(testloader.dataset)
        print(f'====> Validation set loss: {test_loss:.9f}')
    return opt_threshold, max_threat_score

In [5]:
model = UNet2(1)
model.load_state_dict(torch.load('models/unet_single_2_Roadmap_model_final.pth'))
model.eval()

UNet2(
  (dconv_down1): Sequential(
    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
    (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): LeakyReLU(negative_slope=0.1)
    (5): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (dconv_down2): Sequential(
    (0): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): LeakyReLU(negative_slope=0.1)
    (2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): LeakyReLU(negative_slope=0.1)
    (5): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (dconv_down3): Sequential(
    (0): Conv2d(32, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Lea

In [6]:
device = 'cpu'

In [8]:
validate_model_Road(model, 2, loss_function_iou, device=device, img_w=100, img_h=100, low=0.49, high=0.51)

Confusion matrix
 tensor([[2.0730e+08, 4.1822e+07],
        [2.6475e+07, 1.2760e+08]])
Class 0
TP 207298048.0, TN 127604936.0, FP 26474900.0, FN 41822024.0
Class 1
TP 127604936.0, TN 207298048.0, FP 41822024.0, FN 26474900.0
Updating threat score from 0.6513717562737129 to 0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334903097/403200000 (83.061283978%) ,
        BB: 
        TP 127604936.0 
        TN 207298048.0
        FP 41822024.0
        FN 26474900.0
        Threat Score 0.6513717562737129
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.0734e+08, 4.1780e+07],
        [2.6485e+07, 1.2760e+08]])
Class 0
TP 207339808.0, TN 127595048.0, FP 26484814.0, FN 41780472.0
Class 1
TP 127595048.0, TN 207339808.0, FP 41780472.0, FN 26484814.0
Updating threat score from 0.6514593541798069 to 0.6513717562737129

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334934697/403200000 (83.069121280%) ,
        BB: 
        TP 127595048.0 
        TN 207339808.0
        FP 41780472.0
        FN 26484814.0
        Threat Score 0.6514593541798069
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


(0.51, 0.6514593541798069)

In [ ]:
validate_model_Road(model=model, 
                  num_points=49, 
                  loss_function=loss_function_iou, 
                  device=device)

Confusion matrix
 tensor([[2.0417e+08, 4.4949e+07],
        [2.5835e+07, 1.2824e+08]])
Class 0
TP 204171312.0, TN 128244784.0, FP 25835092.0, FN 44948768.0
Class 1
TP 128244784.0, TN 204171312.0, FP 44948768.0, FN 25835092.0
Updating threat score from 0.6443534156692223 to 0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 332416140/403200000 (82.444479167%) ,
        BB: 
        TP 128244784.0 
        TN 204171312.0
        FP 44948768.0
        FN 25835092.0
        Threat Score 0.6443534156692223
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.0527e+08, 4.3854e+07],
        [2.6050e+07, 1.2803e+08]])
Class 0
TP 205266144.0, TN 128029696.0, FP 26050178.0, FN 43853972.0
Class 1
TP 128029696.0, TN 205266144.0, FP 43853972.0, FN 26050178.0
Updating threat score from 0.6468307592072179 to 0.6443534156692223

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 333295826/403200000 (82.662655258%) ,
        BB: 
        TP 128029696.0 
        TN 205266144.0
        FP 43853972.0
        FN 26050178.0
        Threat Score 0.6468307592072179
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[4.0983e+08, 8.8411e+07],
        [5.1963e+07, 2.5620e+08]])
Class 0
TP 409829248.0, TN 256196608.0, FP 51963180.0, FN 88410816.0
Class 1
TP 256196608.0, TN 409829248.0, FP 88410816.0, FN 51963180.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 333609863/403200000 (82.740541419%) ,
        BB: 
        TP 256196608.0 
        TN 409829248.0
        FP 88410816.0
        FN 51963180.0
        Threat Score 0.6460302734702023
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[4.1116e+08, 8.7080e+07],
        [5.2225e+07, 2.5593e+08]])
Class 0
TP 411160320.0, TN 255934960.0, FP 52224956.0, FN 87079864.0
Class 1
TP 255934960.0, TN 411160320.0, FP 87079864.0, FN 52224956.0
Updating threat score from 0.6475435306389811 to 0.6468307592072179

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 333799328/403200000 (82.787531746%) ,
        BB: 
        TP 255934960.0 
        TN 411160320.0
        FP 87079864.0
        FN 52224956.0
        Threat Score 0.6475435306389811
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[6.1589e+08, 1.3147e+08],
        [7.8171e+07, 3.8407e+08]])
Class 0
TP 615893184.0, TN 384068192.0, FP 78171376.0, FN 131467144.0
Class 1
TP 384068192.0, TN 615893184.0, FP 131467144.0, FN 78171376.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 333935407/403200000 (82.821281498%) ,
        BB: 
        TP 384068192.0 
        TN 615893184.0
        FP 131467144.0
        FN 78171376.0
        Threat Score 0.6468988808157068
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[6.1736e+08, 1.3000e+08],
        [7.8460e+07, 3.8378e+08]])
Class 0
TP 617356736.0, TN 383780032.0, FP 78459744.0, FN 130003064.0
Class 1
TP 383780032.0, TN 617356736.0, FP 130003064.0, FN 78459744.0
Updating threat score from 0.6480112913687078 to 0.6475435306389811

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334042037/403200000 (82.847727431%) ,
        BB: 
        TP 383780032.0 
        TN 617356736.0
        FP 130003064.0
        FN 78459744.0
        Threat Score 0.6480112913687078
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[8.2220e+08, 1.7428e+08],
        [1.0443e+08, 5.1189e+08]])
Class 0
TP 822199040.0, TN 511891072.0, FP 104428248.0, FN 174280608.0
Class 1
TP 511891072.0, TN 822199040.0, FP 174280608.0, FN 104428248.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334129666/403200000 (82.869460813%) ,
        BB: 
        TP 511891072.0 
        TN 822199040.0
        FP 174280608.0
        FN 104428248.0
        Threat Score 0.6474717364993452
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[8.2376e+08, 1.7272e+08],
        [1.0474e+08, 5.1158e+08]])
Class 0
TP 823757632.0, TN 511584000.0, FP 104735536.0, FN 172722640.0
Class 1
TP 511584000.0, TN 823757632.0, FP 172722640.0, FN 104735536.0
Updating threat score from 0.6483607791328001 to 0.6480112913687078

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334204681/403200000 (82.888065724%) ,
        BB: 
        TP 511584000.0 
        TN 823757632.0
        FP 172722640.0
        FN 104735536.0
        Threat Score 0.6483607791328001
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.0287e+09, 2.1692e+08],
        [1.3072e+08, 6.3968e+08]])
Class 0
TP 1028683520.0, TN 639678272.0, FP 130720912.0, FN 216916560.0
Class 1
TP 639678272.0, TN 1028683520.0, FP 216916560.0, FN 130720912.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334271219/403200000 (82.904568204%) ,
        BB: 
        TP 639678272.0 
        TN 1028683520.0
        FP 216916560.0
        FN 130720912.0
        Threat Score 0.647896376230261
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.0303e+09, 2.1528e+08],
        [1.3104e+08, 6.3936e+08]])
Class 0
TP 1030315840.0, TN 639355584.0, FP 131043584.0, FN 215284720.0
Class 1
TP 639355584.0, TN 1030315840.0, FP 215284720.0, FN 131043584.0
Updating threat score from 0.6486415994066999 to 0.6483607791328001

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334329939/403200000 (82.919131696%) ,
        BB: 
        TP 639355584.0 
        TN 1030315840.0
        FP 215284720.0
        FN 131043584.0
        Threat Score 0.6486415994066999
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.2353e+09, 2.5941e+08],
        [1.5704e+08, 7.6744e+08]])
Class 0
TP 1235310464.0, TN 767435584.0, FP 157043168.0, FN 259410688.0
Class 1
TP 767435584.0, TN 1235310464.0, FP 259410688.0, FN 157043168.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334383776/403200000 (82.932484127%) ,
        BB: 
        TP 767435584.0 
        TN 1235310464.0
        FP 259410688.0
        FN 157043168.0
        Threat Score 0.6482324943648791
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.2370e+09, 2.5772e+08],
        [1.5738e+08, 7.6710e+08]])
Class 0
TP 1237004544.0, TN 767099264.0, FP 157379248.0, FN 257715168.0
Class 1
TP 767099264.0, TN 1237004544.0, FP 257715168.0, FN 157379248.0
Updating threat score from 0.6488778339451496 to 0.6486415994066999

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334434023/403200000 (82.944946181%) ,
        BB: 
        TP 767099264.0 
        TN 1237004544.0
        FP 257715168.0
        FN 157379248.0
        Threat Score 0.6488778339451496
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.4421e+09, 3.0178e+08],
        [1.8339e+08, 8.9517e+08]])
Class 0
TP 1442058880.0, TN 895166784.0, FP 183391600.0, FN 301781888.0
Class 1
TP 895166784.0, TN 1442058880.0, FP 301781888.0, FN 183391600.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334480397/403200000 (82.956447669%) ,
        BB: 
        TP 895166784.0 
        TN 1442058880.0
        FP 301781888.0
        FN 183391600.0
        Threat Score 0.6485116389613451
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.4438e+09, 3.0003e+08],
        [1.8374e+08, 8.9482e+08]])
Class 0
TP 1443810176.0, TN 894818688.0, FP 183739840.0, FN 300029856.0
Class 1
TP 894818688.0, TN 1443810176.0, FP 300029856.0, FN 183739840.0
Updating threat score from 0.6490832779491453 to 0.6488778339451496

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334524747/403200000 (82.967447173%) ,
        BB: 
        TP 894818688.0 
        TN 1443810176.0
        FP 300029856.0
        FN 183739840.0
        Threat Score 0.6490832779491453
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.6489e+09, 3.4404e+08],
        [2.0976e+08, 1.0229e+09]])
Class 0
TP 1648919552.0, TN 1022873792.0, FP 209763952.0, FN 344042656.0
Class 1
TP 1022873792.0, TN 1648919552.0, FP 344042656.0, FN 209763952.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334566876/403200000 (82.977895833%) ,
        BB: 
        TP 1022873792.0 
        TN 1648919552.0
        FP 344042656.0
        FN 209763952.0
        Threat Score 0.6487514913358018
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.6507e+09, 3.4224e+08],
        [2.1012e+08, 1.0225e+09]])
Class 0
TP 1650722176.0, TN 1022515008.0, FP 210124048.0, FN 342238400.0
Class 1
TP 1022515008.0, TN 1650722176.0, FP 342238400.0, FN 210124048.0
Updating threat score from 0.6492664013270772 to 0.6490832779491453

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334607080/403200000 (82.987867063%) ,
        BB: 
        TP 1022515008.0 
        TN 1650722176.0
        FP 342238400.0
        FN 210124048.0
        Threat Score 0.6492664013270772
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.8559e+09, 3.8620e+08],
        [2.3616e+08, 1.1506e+09]])
Class 0
TP 1855880448.0, TN 1150557568.0, FP 236159664.0, FN 386201344.0
Class 1
TP 1150557568.0, TN 1855880448.0, FP 386201344.0, FN 236159664.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334645512/403200000 (82.997398810%) ,
        BB: 
        TP 1150557568.0 
        TN 1855880448.0
        FP 386201344.0
        FN 236159664.0
        Threat Score 0.6489624592608465
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[1.8577e+09, 3.8435e+08],
        [2.3653e+08, 1.1502e+09]])
Class 0
TP 1857733248.0, TN 1150186240.0, FP 236531088.0, FN 384348352.0
Class 1
TP 1150186240.0, TN 1857733248.0, FP 384348352.0, FN 236531088.0
Updating threat score from 0.6494317075961169 to 0.6492664013270772

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334682708/403200000 (83.006624008%) ,
        BB: 
        TP 1150186240.0 
        TN 1857733248.0
        FP 384348352.0
        FN 236531088.0
        Threat Score 0.6494317075961169
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.0629e+09, 4.2826e+08],
        [2.6258e+08, 1.2782e+09]])
Class 0
TP 2062936448.0, TN 1278219008.0, FP 262577248.0, FN 428264288.0
Class 1
TP 1278219008.0, TN 2062936448.0, FP 428264288.0, FN 262577248.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334718897/403200000 (83.015599454%) ,
        BB: 
        TP 1278219008.0 
        TN 2062936448.0
        FP 428264288.0
        FN 262577248.0
        Threat Score 0.649151683196945
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.0648e+09, 4.2637e+08],
        [2.6296e+08, 1.2778e+09]])
Class 0
TP 2064834944.0, TN 1277838080.0, FP 262959472.0, FN 426365792.0
Class 1
TP 1277838080.0, TN 2064834944.0, FP 426365792.0, FN 262959472.0
Updating threat score from 0.649584109381393 to 0.6494317075961169

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334754247/403200000 (83.024366815%) ,
        BB: 
        TP 1277838080.0 
        TN 2064834944.0
        FP 426365792.0
        FN 262959472.0
        Threat Score 0.649584109381393
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.2701e+09, 4.7024e+08],
        [2.8902e+08, 1.4059e+09]])
Class 0
TP 2270086144.0, TN 1405859712.0, FP 289016448.0, FN 470237280.0
Class 1
TP 1405859712.0, TN 2270086144.0, FP 470237280.0, FN 289016448.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334788151/403200000 (83.032775546%) ,
        BB: 
        TP 1405859712.0 
        TN 2270086144.0
        FP 470237280.0
        FN 289016448.0
        Threat Score 0.6493238406644821
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.2720e+09, 4.6830e+08],
        [2.8941e+08, 1.4055e+09]])
Class 0
TP 2272025856.0, TN 1405468800.0, FP 289408896.0, FN 468295104.0
Class 1
TP 1405468800.0, TN 2272025856.0, FP 468295104.0, FN 289408896.0
Updating threat score from 0.6497256060253537 to 0.649584109381393

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334821472/403200000 (83.041039683%) ,
        BB: 
        TP 1405468800.0 
        TN 2272025856.0
        FP 468295104.0
        FN 289408896.0
        Threat Score 0.6497256060253537
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.4773e+09, 5.1212e+08],
        [3.1548e+08, 1.5335e+09]])
Class 0
TP 2477318400.0, TN 1533480448.0, FP 315475840.0, FN 512123488.0
Class 1
TP 1533480448.0, TN 2477318400.0, FP 512123488.0, FN 315475840.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334854443/403200000 (83.049217014%) ,
        BB: 
        TP 1533480448.0 
        TN 2477318400.0
        FP 512123488.0
        FN 315475840.0
        Threat Score 0.6494826827979887
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.4793e+09, 5.1014e+08],
        [3.1588e+08, 1.5331e+09]])
Class 0
TP 2479303424.0, TN 1533079040.0, FP 315878720.0, FN 510138720.0
Class 1
TP 1533079040.0, TN 2479303424.0, FP 510138720.0, FN 315878720.0
Updating threat score from 0.6498585329641037 to 0.6497256060253537

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334886747/403200000 (83.057228919%) ,
        BB: 
        TP 1533079040.0 
        TN 2479303424.0
        FP 510138720.0
        FN 315878720.0
        Threat Score 0.6498585329641037
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.6846e+09, 5.5392e+08],
        [3.4196e+08, 1.6611e+09]])
Class 0
TP 2684641280.0, TN 1661080576.0, FP 341955584.0, FN 553924096.0
Class 1
TP 1661080576.0, TN 2684641280.0, FP 553924096.0, FN 341955584.0

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334919039/403200000 (83.065237847%) ,
        BB: 
        TP 1661080576.0 
        TN 2684641280.0
        FP 553924096.0
        FN 341955584.0
        Threat Score 0.6496309718159342
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.


Confusion matrix
 tensor([[2.6867e+09, 5.5190e+08],
        [3.4237e+08, 1.6607e+09]])
Class 0
TP 2686665984.0, TN 1660669184.0, FP 342368512.0, FN 551897600.0
Class 1
TP 1660669184.0, TN 2686665984.0, FP 551897600.0, FN 342368512.0
Updating threat score from 0.6499848299876476 to 0.6498585329641037

Validation set: 
        Average loss: -373.055912412, 
        Accuracy BB: 334950851/403200000 (83.073127728%) ,
        BB: 
        TP 1660669184.0 
        TN 2686665984.0
        FP 551897600.0
        FN 342368512.0
        Threat Score 0.6499848299876476
====> Validation set loss: -0.592152242


/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1587428207430/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
